<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2026 Aiven Oy

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.aiven.kafka.connect</groupId>
    <artifactId>connectors-for-salesforce</artifactId>
    <version>0.4.0</version>
  </parent>

  <artifactId>source-connector-for-salesforce</artifactId>
  <name>Aiven source connector for Salesforce on Apache Kafka</name>
  <description>Apache Kafka connector to extract data from Salesforce</description>

  <inceptionYear>2026</inceptionYear>

  <distributionManagement>
    <snapshotRepository>
      <id>central-snapshot</id>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
    </snapshotRepository>
    <site>
      <id>staging</id>
      <!--  For the URL to resolve to the default URL as described in the Apache Site Plugin documentation this URL
                  must be invalid. A ticket is open to resolve this issue. See https://github.com/apache/maven-site-plugin/issues/1140
                  -->
      <url>invalid:url/source</url>
    </site>
  </distributionManagement>

  <properties>
    <io.aiven.kafka.connect.source-connector-for-salesforce.version>${project.version}</io.aiven.kafka.connect.source-connector-for-salesforce.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.aiven.commons</groupId>
      <artifactId>framework-for-source-connectors</artifactId>
      <version>${aiven.framework.version}</version>
    </dependency>
    <dependency>
      <groupId>io.aiven.kafka.connect</groupId>
      <artifactId>connector-common-for-salesforce</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-markdown-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>pre-site</phase>
            <configuration>
              <overwrite>true</overwrite>
              <resources>
                <resource>
                  <directory>src/site/resources</directory>
                  <includes>
                    <include>config_example.txt</include>
                  </includes>
                </resource>
              </resources>
              <outputDirectory>src/site/markdown</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>properties-maven-plugin</artifactId>
        <version>1.3.0</version>
        <executions>
          <execution>
            <goals>
              <goal>write-project-properties</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <outputFile>${project.build.outputDirectory}/${project.groupId}/${project.artifactId}.properties</outputFile>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.rat</groupId>
        <artifactId>apache-rat-plugin</artifactId>
        <configuration>
          <inputExclude>src/site/resources/config_example.txt</inputExclude>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>single</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <finalName>${project.artifactId}-${project.version}</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <descriptors>
                <descriptor>src/main/assembly/release.xml</descriptor>
              </descriptors>
              <tarLongFileMode>posix</tarLongFileMode>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
            </manifest>
            <manifestEntries>
              <Specification-Vendor>Apache Kafka</Specification-Vendor>
              <Specification-Version>${kafka.version}</Specification-Version>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <publishingServerId>central</publishingServerId>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-site-plugin</artifactId>
        <configuration>
          <generateReports>false</generateReports>
          <generateProjectInfo>false</generateProjectInfo>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.apache.maven.doxia</groupId>
            <artifactId>doxia-module-markdown</artifactId>
            <version>2.0.0</version>
          </dependency>
          <dependency>
            <groupId>org.apache.maven.doxia</groupId>
            <artifactId>doxia-site-renderer</artifactId>
            <version>2.0.0</version>
          </dependency>
          <dependency>
            <groupId>io.aiven.commons</groupId>
            <artifactId>kafka-config</artifactId>
            <version>${aiven.kafka.config.version}</version>
          </dependency>
          <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>${project.artifactId}</artifactId>
            <version>${project.version}</version>
          </dependency>
          <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>${kafka.version}</version>
          </dependency>
          <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-api</artifactId>
            <version>${kafka.version}</version>
          </dependency>
          <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-runtime</artifactId>
            <version>${kafka.version}</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
</project>
